### ISSUE TITLE
subnet formatting

### ISSUE THREAD

**Issue by midacts** [Azure/terraform-azurerm-vnet#11]
Would this project be willing to change the subnet information into a list similar to how the [terraform_auzrerm_netowrk_security_group](https://github.com/Azure/terraform-azurerm-network-security-group/blob/master/variables.tf#L31-L35) project does their NSG rules?

It makes it so all the subnet information is logically together:
```hcl
    subnets = [
        {
            subnet_name                     = ...
            resource_group_name       = ...
            virtual_network_name        = ...
            subnet_address_prefix        = ...
            route_table_id                     = ...
            network_security_group_id = ...
        },
        {
            subnet_name                     = ...
            resource_group_name       = ...
            virtual_network_name        = ...
            subnet_address_prefix        = ...
            route_table_id                     = ...
            network_security_group_id = ...
        },
        ...
    ]
```
instead of:
```hcl
    subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
    subnet_names        = ["subnet1", "subnet2", "subnet3"]
    nsg_ids = {
        subnet1 = "nsgid1"
        subnet2 = "nsgid2"
        subnet3 = "nsgid3"
    }
    ...
```

**Comment by sblack4** [comment]
I was going to suggest the same thing. This module is done really well and has done something similar: https://registry.terraform.io/modules/nlarzon/vnet/azure/0.9.2

**Comment by yupwei68** [comment]
Hi @midacts , Thanks for opening this issue. Sorry for the delay. But currently, resource "azurerm_virtual_network" support this skema. Please refer to https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html. So we don't duplicate this function and keep our original skema.
