### ISSUE TITLE
Deprecated fields `enforce_private_link_endpoint_network_policies` and `enforce_private_link_service_network_policies` in `azurerm_subnet` resource

### ISSUE THREAD

**Issue by ahublersos** [Azure/terraform-azurerm-vnet#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Both the `azurerm_subnet.subnet_count` and `azurerm_subnet.subnet_for_each` use the `enforce_private_link_endpoint_network_policies` and `enforce_private_link_service_network_policies` properties which are deprecated and will be removed in version 4.0 of the AzureRM provider. 

The terraform-azurerm-vnet module should be updated to use `private_endpoint_network_policies_enabled` and `private_link_service_network_policies_enabled` properties instead.

This deprecation message is shown whenever the terraform-azurerm-vnet module is used.
```
╷
│ Warning: Argument is deprecated
│ 
│   with module.vnet.azurerm_subnet.subnet_for_each["GatewaySubnet"],
│   on .terraform/modules/vnet/main.tf line 57, in resource "azurerm_subnet" "subnet_for_each":
│   57:   enforce_private_link_endpoint_network_policies = lookup(var.subnet_enforce_private_link_endpoint_network_policies, each.value, false)
│ 
│ `enforce_private_link_endpoint_network_policies` will be removed in favour of the property `private_endpoint_network_policies_enabled` in version 4.0 of the AzureRM Provider
│ 
│ (and one more similar warning elsewhere)
```

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### References

AzureRM provider PR that deprecated the `enforce_private_link_endpoint_network_policies` and `enforce_private_link_service_network_policies` fields: [PR 17464](https://github.com/hashicorp/terraform-provider-azurerm/pull/17464)

**Comment by lonegunmanb** [comment]
Thanks @ahublersos for opening this issue. According to the [provider schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/subnet_resource.go#L170-L188), these two new fields would be added into `azurerm_subnet` resource in 4.0 so we have nothing to do in 3.x.

This module has already [locked provider's version to 3.x](https://github.com/Azure/terraform-azurerm-vnet/blob/main/versions.tf#L7) so we won't have any breaking change. When AzureRM provider has launched 4.0, we'll publish a major version upgrade for this module which contains breaking changes. Thanks for your concern, would you please stay tuned on this module and help us by verifying our next major version when AzureRM 4.0 has been published? Thanks a lot!

**Comment by atz** [comment]
Relates to https://github.com/Azure/terraform-azurerm-vnet/issues/69

Strategy makes sense... still waiting on 4.x provider.

**Comment by zalex-1** [comment]
Is there an update?

**Comment by fabienbeller** [comment]
The day has arrived. Version 4.x has been published. Is there a major version upgrade for this still in the works?

**Comment by mfornasa** [comment]
> When AzureRM provider has launched 4.0, we'll publish a major version upgrade for this module which contains breaking changes.

Hello @lonegunmanb. Is there a planned target date for the upgrade to AzureRM version 4? Thanks.
