### ISSUE TITLE
Second run after a modification results in the network group not applying

### ISSUE THREAD

**Issue by bfleming-ciena** [Azure/terraform-azurerm-vnet#13]
I'm using the example right off the web page.  subnet1 is assigned the network security group "ssh".

I was calling this module from within another module that I own.  It worked fine the first time.  But I'm re-orging some of terrform into separate files and it triggered a change, and it is removing the "ssh" security group.

`
# Create the resource group and network
module "network" {
  source              = "Azure/network/azurerm"
  resource_group_name = "${var.resource_group}"
  location            = "westus"
  address_space       = "10.0.0.0/16"
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]
  vnet_name           = "${var.vnet_name}"

  tags = {
    environment = "${var.environment_tag}"
    terraform = "true"
  }
}

resource "azurerm_subnet" "subnet" {
  name  = "subnet1"
  depends_on          = ["azurerm_network_security_group.ssh"]
  address_prefix = "10.0.1.0/24"
  resource_group_name = "${var.resource_group}"
  virtual_network_name = "${var.vnet_name}"
  network_security_group_id = "${azurerm_network_security_group.ssh.id}"
}

resource "azurerm_network_security_group" "ssh" {
  
  name                = "ssh"
  location            = "westus"
  resource_group_name = "${var.resource_group}"

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

output "ssh" {
  value = "${azurerm_network_security_group.ssh.name}"
}

output "subnet" {
  value = "${azurerm_subnet.subnet.name}"
}

output "subnet_ids" {
  value = "${module.network.vnet_subnets}"
}
`

Same code, just re-orged some things and I get this.  It is removing the sg, even though my state says it should be there. I have a feeling this is somehow related to the depends_on.

`
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.vnet.azurerm_subnet.subnet
      network_security_group_id: "/subscriptions/xxxxxxxx/resourceGroups/DevGroup/providers/Microsoft.Network/networkSecurityGroups/ssh" => "/subscriptions/xxxxx/resourceGroups/terraform-dev/providers/Microsoft.Network/networkSecurityGroups/ssh"

  ~ module.vnet.module.network.azurerm_subnet.subnet[0]
      network_security_group_id: "/subscriptions/xxxxxxxx/resourceGroups/DevGroup/providers/Microsoft.Network/networkSecurityGroups/ssh" => ""

Plan: 0 to add, 2 to change, 0 to destroy.
`

**Comment by nidhi5885** [comment]
Any solution to above stated problem?

**Comment by yupwei68** [comment]
Hi @bfleming-ciena ,we'll fix it in the next release.
