### ISSUE TITLE
Do not default random tags in a reusable module

### ISSUE THREAD

**Issue by KevinBrooke** [Azure/terraform-azurerm-vnet#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Companies use systems to verify resources have tags assigned and this module passes the test as it is setting a default tag. This should be defaulted to {} to ensure users of the module are declaring their own tags.

variable "tags" {
  type = map(string)
  default = {
    ENV = "test"
  }
  description = "The tags to associate with your network and subnets."
}

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network

### Potential Terraform Configuration

```hcl
variable "tags" {
  type = map(string)
  default = {}
  description = "The tags to associate with your network and subnets."
}
```

**Comment by lonegunmanb** [comment]
Thanks @KevinBrooke, I agree with you. But removing the default value would be considered as breaking change, so we would fix this issue in our next major version upgrade.

I'll let you know when we have progress, again, thanks for your suggestion!
