### ISSUE TITLE
Using `network_security_group_id` on `azurerm_subnet` resources is deprecated

### ISSUE THREAD

**Issue by rosstimson** [Azure/terraform-azurerm-vnet#15]
Currently get the following deprecation warnings for every subnet:

```
Warning: module.vnet.azurerm_subnet.subnet[0]: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.
```

## Module Version

```
module "vnet" {
  source              = "Azure/vnet/azurerm"
  version             = "1.2.0"
```

## Terraform Version

```
terraform -v
Terraform v0.11.10
+ provider.aws v1.38.0
+ provider.azurerm v1.17.0
+ provider.random v2.0.0
```

**Comment by opticyclic** [comment]
It isn't marked as deprecated in the docs here:
https://www.terraform.io/docs/providers/azurerm/d/subnet.html#network_security_group_id

However, confusingly, the deprecation **is** marked here
https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html

So you need to add something like

    resource "azurerm_subnet_network_security_group_association" "test" {
      subnet_id                 = "${azurerm_subnet.test.id}"
      network_security_group_id = "${azurerm_network_security_group.test.id}"
    }

However, the docs say:

> NOTE: Subnet <-> Network Security Group associations currently need to be configured on both this resource and using the network_security_group_id field on the azurerm_subnet resource. 

Which implies that you can't remove the deprecated property anyway!

**Comment by yupwei68** [comment]
Hi @rosstimson , it'll be fixed in the next release.

**Comment by amenocal** [comment]
@yupwei68 why is this network_security_group_id feature removed? We have certain policies in our azure tenants and we can't create vnets withouth tying it to a nsg. How hard/complex would be to bring it back?

**Comment by yupwei68** [comment]
@amenocal, it's the change of Azurerm 2.0. You could use [subnet_network_security_group_association](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html )instead.
