### ISSUE TITLE
Support for Private DNS

### ISSUE THREAD

**Issue by dkossako** [Azure/terraform-azurerm-vnet#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

do you think is it worth to implement Private DNS support in this vnet module? I know it's technically different part of azure service, but imo in most cases vnet setup is related to private dns setup. It's needed to allow us to connect to many services over LAN connections.

I can take care about implementation, but question is whether it makes sense?

### New or Affected Resource(s)/Data Source(s)

azurerm_private_dns_zone

**Comment by ShehzadMohammed** [comment]
I don't think it makes sense here... It would be over-coupling this module. It can be implemented via a separate module.

**Comment by lonegunmanb** [comment]
@dkossako thanks for opening this issue to us, and I agree with @ShehzadMohammed , this feature should be put in a separated module, so I'm closing this issue now.
