### ISSUE TITLE
Error: Cycle

### ISSUE THREAD

**Issue by Tajjun** [Azure/terraform-azurerm-vnet#31]
Running the following code

``provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "tf-vnet-test-rg"
  location = "West Europe"
}

module "vnet" {
  source              = "Azure/vnet/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]

  nsg_ids = {
    subnet1 = azurerm_network_security_group.ssh.id
    subnet2 = azurerm_network_security_group.ssh.id
    subnet3 = azurerm_network_security_group.ssh.id
  }

  tags = {
    environment = "dev"
    costcenter  = "it"
  }
}

resource "azurerm_network_security_group" "ssh" {
  depends_on          = [module.vnet]
  name                = "ssh"
  location            = "westus"
  resource_group_name = var.resource_group_name

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }

}
``

getting the following error `Error: Cycle: module.vnet.azurerm_subnet_network_security_group_association.vnet, azurerm_network_security_group.ssh, module.vnet.var.nsg_ids, module.vnet.data.azurerm_subnet.import, module.vnet.azurerm_subnet_route_table_association.vnet`

**Comment by yupwei68** [comment]
Hi @Tajjun , thanks for opening this issue. The NSG is not dependent on the module `vnet`, I have deleted the dependent line and update the `resource_group_name` in `azurerm_network_security_group`. The code below works fine for me.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "tf-vnet-test-rg"
  location = "West Europe"
}

module "vnet" {
  source              = "Azure/vnet/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]

  nsg_ids = {
    subnet1 = azurerm_network_security_group.ssh.id
    subnet2 = azurerm_network_security_group.ssh.id
    subnet3 = azurerm_network_security_group.ssh.id
  }

  tags = {
    environment = "dev"
    costcenter  = "it"
  }
}

resource "azurerm_network_security_group" "ssh" {
  name                = "ssh"
  location            = "westus"
  resource_group_name = azurerm_resource_group.example.name

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = ""
    destination_port_range     = "22"
    source_address_prefix      = ""
    destination_address_prefix = "*"
  }

}
```
