### ISSUE TITLE
datasource resource group assumes its built outside of the current TF

### ISSUE THREAD

**Issue by ragarcia26** [Azure/terraform-azurerm-vnet#32]
```
Error: Error: Resource Group "aks-ricky-test" was not found
  on .terraform/modules/network/main.tf line 2, in data "azurerm_resource_group" "vnet":
   2: data azurerm_resource_group "vnet" {
```
Unable to use this module if the resource group passed is in the same TF build as per how datasources work.

**Comment by ragarcia26** [comment]
Datasources are used to query against existing resources (for example the subscription you are in), they are queried and retrieved before even the terraform graph is created and shouldn't be part of the build cycle.  
I noticed theres datasource usage in acquiring the subnet id's from within the module itself https://github.com/Azure/terraform-azurerm-vnet/blob/master/main.tf#L23 this works?  why not just use the id's from the subnets you created right above it -> "azurerm_subnet" "subnet" and if it needs to be indexed by name just create that via a loop

**Comment by ragarcia26** [comment]
for example re written - 
```
resource azurerm_virtual_network "vnet" {
  name                = var.vnet_name
  resource_group_name = var.resource_group_name
  location            = var.location
  address_space       = var.address_space
  dns_servers         = var.dns_servers
  tags                = var.tags
}

resource "azurerm_subnet" "subnet" {
  count                = length(var.subnet_names)
  name                 = var.subnet_names[count.index]
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = [var.subnet_prefixes[count.index]]
}

locals {
  azurerm_subnets = {
    for index, subnet in azurerm_subnet.subnet: 
      subnet.name => subnet.id
  }
}

resource "azurerm_subnet_network_security_group_association" "vnet" {
  for_each                  = var.nsg_ids
  subnet_id                 = local.azurerm_subnets[each.key]
  network_security_group_id = each.value
}

resource "azurerm_subnet_route_table_association" "vnet" {
  for_each       = var.route_tables_ids
  route_table_id = each.value
  subnet_id      = local.azurerm_subnets[each.key]
}
```
location is still an extra variable that i'm sure you were hoping to remove but i'm not sure thats possible in what i did. You could make an assumption that the client is in the same location as the location and datasource that, and have it overridable in case not. but maybe thats not a good assumption

**Comment by yupwei68** [comment]
Hi @ragarcia26 , thanks for opening this issue. Thanks for your suggestion. Have you upgraded terraform version to 0.13? Would you like to add a dependency in the modules to solve this problem like:
```
module "vnet" {
  source              = "Azure/vnet/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]

  tags = {
    environment = "dev"
    costcenter  = "it"
  }

  depends_on = [azurerm_resource_group.example]
}
```

**Comment by chrizkim** [comment]
@yupwei68 Ran into the same issue after upgrading to 0.13 but the new support for `depends_on` in the module resolves it, thanks
