### ISSUE TITLE
Cannot parse Azure ID: parse "azurerm_mssql_server.db_server.id": invalid URI for request

### ISSUE THREAD

**Issue by chakri1082** [Azure/terraform-azurerm-vnet#56]
I am trying to enable diagnostic setting for Azure SQL Database and I am getting this error for server ID.

**Comment by lonegunmanb** [comment]
Hi @chakri1082 thanks for open this issue and apology for the late reply, would you please give us a minimum sample that could reproduce this issue? Thanks!

**Comment by lonegunmanb** [comment]
I'm closing this issue since we have no response from the user. Please feel free to reopen it if you have any further question, thanks!
