### ISSUE TITLE
Subnet delegation syntax

### ISSUE THREAD

**Issue by eliesadjal** [Azure/terraform-azurerm-vnet#59]
Would like to add a service delegation to my subnet but do not know the syntax to associate a subnet to a subnet delegation ? Thank you

**Comment by lonegunmanb** [comment]
Hello @eliesadjal thanks for opening this issue and apology for this late reply. Would you please take a look at this [example](https://github.com/Azure/terraform-azurerm-vnet/blob/master/examples/complete/main.tf#L39-L50)? Please feel free to ping me if you have any further question.

**Comment by lonegunmanb** [comment]
I'm closing this issue since we have no response from the user. Please feel free to reopen it if you have any further question.
