### ISSUE TITLE
Circular dependency on resource group

### ISSUE THREAD

**Issue by adhodgson1** [Azure/terraform-azurerm-vnet#62]
I have a circular dependency with this module whereby on a new deployment it fails to find the resource group. On closer inspection this is due to the data lookup to find the vnet location from the resource group location. I have worked around this by adding a dependency to the calling modules on the resource group, however as its a hard dependency a tag change for example on the resource group causes the attempted destruction of the virtual network and everything else that relies on it.

I have seen the issue #43 but the reason I am creating my own issue is because I potentially have a way to fix this without causing a braking change.

If we make the data lookup happen only if the vnet_location variable is not defined:
```
data "azurerm_resource_group" "vnet" {
  count = var.vnet_location != null ? 0 : 1
  name = var.resource_group_name
}
```

We can then specify the resource group name explicitly (remove the data source) and only use it if the vnet_location is not defined:
```
resource "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  resource_group_name = var.resource_group_name
  location            = var.vnet_location != null ? var.vnet_location : data.azurerm_resource_group.vnet[0].location
[...]
}

resource "azurerm_subnet" "subnet" {
  count                                          = length(var.subnet_names)
  name                                           = var.subnet_names[count.index]
  resource_group_name                            = var.resource_group_name
[...]
}

To be clear I prefer the suggested solution in #43 but wanted to suggest a possible way forward that didn't involve a breaking change.

**Comment by lonegunmanb** [comment]
@adhodgson1 Thanks for opening this issue. I agree since I've met the very problem too. I think your suggestion is awesome and I'll see what I can to for that.
