### ISSUE TITLE
enforce_private_link_endpoint_network_policies Deprecation warning when using azurerm v3.24.0

### ISSUE THREAD

**Issue by adhodgson-wpp** [Azure/terraform-azurerm-vnet#69]
When using azurerm v3.24.0 we get the following deprecation warning when running a plan with this module:

│ Warning: Argument is deprecated
│
│   with module.firewall.module.network.azurerm_subnet.subnet,
│   on .terraform\modules\firewall.network\main.tf line 22, in resource "azurerm_subnet" "subnet":
│   22:   enforce_private_link_endpoint_network_policies = lookup(var.subnet_enforce_private_link_endpoint_network_policies, var.subnet_names[count.index], false)
│
│ `enforce_private_link_endpoint_network_policies` will be removed in favour of the property
│ `private_endpoint_network_policies_enabled` in version 4.0 of the AzureRM Provider

**Comment by holms** [comment]
Got the same warning, I hope with 4.0 version I won't have problem using this module in production?

**Comment by lonegunmanb** [comment]
It will be a breaking change since the `private_endpoint_network_policies_enabled` will only be available in 4.0, we might need to limit this module's `azurerm` provider's version to `< 4.0` to avoid potential breaking change.
