### ISSUE TITLE
Get resource group not found error

### ISSUE THREAD

**Issue by fabiomarinetti** [Azure/terraform-azurerm-vnet#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3.5

### Module Version

3.0.0

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
variable "basename" {
  description = "(Required) Specifies the prefix to prepend to resource groups and resources name."
  type        = string
}

variable "region" {
  description = "the region where the AKS cluster will be deployed."
  type        = string
  default     = "westeurope"
}

variable "spoke_resource_group_name" {
  description = "Specifies the name of the resource group."
  type        = string
  default     = ""
}

variable "spoke_vnet_address_space" {
  description = "the address prefix of the spoke subnet."
  default     = ["10.0.0.0/16"]
  type        = list(string)
}

variable "gateway_subnet_cidr" {
  description = "the cidr of the spoke subnet application gateway is on."
  type        = string
  default     = "10.0.0.0/24"
}

variable "default_node_pool_subnet_cidr" {
  description = "the cidr of the spoke subnet aks default node pool is on."
  type        = string
  default     = "10.0.1.0/24"
}

variable "tags" {
  description = "the map of tags set on the aks cluster."
  type        = map(string)
  default     = {}
}

locals {
  spoke_vnet_name           = "${var.basename}-spoke"
  spoke_resource_group_name = coalesce(var.spoke_resource_group_name, "${var.basename}-spoke-rg")
  base_tags = {
    Deployment = "Terraform"
    Pricing = "pay-as-you-go"
  }
  tags = merge(local.base_tags, var.tags)
}

resource "azurerm_resource_group" "spoke_rg" {
  name     = local.spoke_resource_group_name
  location = var.region
}

module "spokenet" {
  source  = "Azure/vnet/azurerm"
  version = "3.0.0"

  vnet_name           = local.spoke_vnet_name
  vnet_location       = var.region
  resource_group_name = azurerm_resource_group.spoke_rg.name
  address_space       = var.spoke_vnet_address_space
  subnet_names        = ["AzureAppGatewaySubnet", "AzureDefaultNodePoolSubnet"]
  subnet_prefixes     = [var.gateway_subnet_cidr, var.default_node_pool_subnet_cidr]
  tags                = local.tags

  depends_on = [azurerm_resource_group.spoke_rg]
}
```

### tfvars variables values

```hcl
basename = "capoccione"
```

### Debug Output/Panic Output

```shell
https://gist.github.com/fabiomarinetti/0d368b07ab943fa7f8af00f513c70963
```

### Expected Behaviour

I expect the rgroup is correctly created before the datasource query (within module) given the depends_on constraint.

### Actual Behaviour

Resource group is not found.

### Steps to Reproduce

terraform init
terraform apply

### References

This looks pretty similar to https://github.com/Azure/terraform-azurerm-vnet/issues/62 but the provided workaround did not work for me.

**Comment by lonegunmanb** [comment]
Hello @fabiomarinetti , thanks for opening this issue. I've run your code on my side and everything is fine.

In your debug log's tail we could see the error message:

```text
2022-11-24T09:44:46.567+0100 [ERROR] vertex "module.aks.data.azurerm_resource_group.main" error: Error: Resource Group "capoccione-spoke-rg" was not found
2022-11-24T09:44:46.567+0100 [ERROR] vertex "module.aks.data.azurerm_resource_group.main (expand)" error: Error: Resource Group "capoccione-spoke-rg" was not found
```

The error message complained that `data.azurerm_resource_group.main` cannot find your resource group, but it's from your module `aks`, so I'll suggest you check your code to verify if you have declared a module named `aks`.

Btw, I'm the maintainer of [terraform-azurerm-aks](https://github.com/Azure/terraform-azurerm-aks) module so if you can verify the issue is caused by this module, you're welcomed to raise an issue there.

**Comment by fabiomarinetti** [comment]
Hi @lonegunmanb,

thanks for your prompt reply. 
You are right! I did not update the references in my aks module. Sorry for having annoyed you :(

I close the issue.
Thanks.
